# SPDX-FileCopyrightText: Copyright (c) 2026 Illia Brashkin
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: release
'on':
  push:
    branches:
      - main
permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  pages: write
jobs:
  release-pr:
    runs-on: ubuntu-slim
    outputs:
      created: ${{ steps.release.outputs.release_created }}
    steps:
      - id: release
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
  publish:
    needs: release-pr
    if: ${{ needs.release-pr.outputs.created }}
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: lewagon/wait-on-check-action@369769072fe522a3a8a85c03c96af1e5242a1994 # v1.9.1
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          running-workflow-name: 'publish'
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: mkdir -p pages
      - uses: docker://pandoc/core:3.11@sha256:62518bfb6833705dc90a1634d8d879299bd820b3f74ad3b32fba8b618452553a
        with:
          args: >-
            -s src/presentation.md
            -o pages/index.html
            -t revealjs
            --embed-resources
            --slide-level=3
            -V theme=white
      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: './pages'
      - id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
